### ISSUE TITLE
test run fail

### ISSUE THREAD

**Issue by ansonla3** [djengineer/bounty-dapp#1]
hi, I have tried to run "truffle test" , but got the following errors.

Ansons-MacBook-Pro-131:bounty-dapp anson$ truffle test
Using network 'development'.

Compiling ./contracts/Bounty.sol...
Compiling ./test/TestBounty.sol...
Compiling truffle/Assert.sol...
Compiling truffle/DeployedAddresses.sol...

  TestBounty
    1) "before all" hook: prepare suite

  0 passing (688ms)
  1 failing

  1) TestBounty
       "before all" hook: prepare suite:
     Error: VM Exception while processing transaction: invalid opcode
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1057:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

Is that correct ?

**Comment by djengineer** [comment]
Hi, that is not supposed to happen. i will check on my end to see what is going on here with the "opcode"error

**Comment by djengineer** [comment]
![correct test](https://user-images.githubusercontent.com/17423518/44942479-96dcc680-ade4-11e8-8ff4-c261e6b722b5.JPG)

I have no problems on my VM with truffle compile and truffle test.

Maybe it is a ganache issue? 

Also as a learning experience using JS to write the tests seems to be much more effective at catching the reverts as a successful test. There is a complicated round about way to test for revert with solidity but it seems too complex so i just went with this.
